// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: foo.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getFoo = `-- name: GetFoo :one
SELECT id, area, location FROM foo WHERE id = $1 LIMIT 1
`

type GetFooParams struct {
	ID uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) GetFoo(ctx context.Context, arg GetFooParams) (Foo, error) {
	row := q.db.QueryRow(ctx, getFoo, arg.ID)
	var i Foo
	err := row.Scan(&i.ID, &i.Area, &i.Location)
	return i, err
}
