// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"github.com/google/uuid"
)

type Foo struct {
	ID       uuid.UUID   `json:"id"`
	Area     interface{} `json:"area"`
	Location interface{} `json:"location"`
}
