// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"foo/ewkb"
	"github.com/google/uuid"
)

type Foo struct {
	ID       uuid.UUID  `db:"id" json:"id"`
	Area     ewkb.Any   `db:"area" json:"area"`
	Location ewkb.Point `db:"location" json:"location"`
}
